### ISSUE TITLE
Unable to determine how to stop an Activity

### ISSUE THREAD

**Issue by RaginBajin** [bwssytems/restful-harmony#1]
I am able to start an activity and the documentation is great for that, but I am having a problem figuring out how to stop an activity.    Can someone help me out or give me some insight?

**Comment by bwssytems** [comment]
It is the activity "PowerOff". It is created by default on the hub. It should have been listed in the activities when you called harmony/list/activities.

**Comment by RaginBajin** [comment]
Ahh, thank you for this.. Here's my example for anyone looking it up.. 

curl -XPUT http://127.0.0.1:8081/harmony/start -d "{"activityid" : "PowerOff" }

Now, I just need to figure out how to include this with the echo-bridge so I can say "Turn off TV".
