### ISSUE TITLE
Adding HA Bridge Device into Domoticz?

### ISSUE THREAD

**Issue by Xenderblade** [bwssytems/restful-harmony#11]
Hello,

Can I activate a bridge harmony device (not harmony activity) into domoticz and how?
is there an URL to do that an put it into "Action On" in a domoticz dummy button switch?

My HA Bridge is showing this for my AC Harmony device :
{"device":"48573103","button":"ON Heat 21°","hub":"Harmony Elite"}

Thanks for your help ! ;-)

**Comment by bwssytems** [comment]
FYI, this is in the incorrect issues area as this is another project for the harmony system.

As far as your question, just have domoticz discover the ha-bridge as a philips hue and then call that device.

**Comment by bwssytems** [comment]
Also, a clarification is that the ha-bridge does not expose this api for the restful-harmony.

**Comment by Xenderblade** [comment]
Thanks a lot ! Didn't think about adding HA Bridge into domoticz like a Philipps Hue bridge!
You're the man it's working ! ;-)

**Comment by bwssytems** [comment]
Glad you are set. It's a swiss army knife type of tool.
