### ISSUE TITLE
Example not correct

### ISSUE THREAD

**Issue by glsf91** [bwssytems/restful-harmony#12]
The example on de startpage is not correct:

`[
	{
		"device":"TV","button":"1"
	},
	{
		"device":"TV","button:"2","delay":150,"count":5
	},
	{
		"device":"TV","button:"3"
	}
]`

should be 
`[
	{
		"device":"TV","button":"1"
	},
	{
		"device":"TV","button":"2","delay":150,"count":5
	},
	{
		"device":"TV","button":"3"
	}
]`

**Comment by bwssytems** [comment]
Yep, one quote missing

**Comment by bwssytems** [comment]
Actually 2 quotes missing but now updated. Thanks!
