### ISSUE TITLE
Question/suggestion: How to send multiple keypresses?

### ISSUE THREAD

**Issue by quenthal** [bwssytems/restful-harmony#2]
For example when wanting to to change channel 23, I'd like to be able to sent keypresses 0, 2 and 3 to required device.

**Comment by bwssytems** [comment]
Use the Harmony button page and build the sequence, already available by selecting each item and pressing the build button.
On Mar 24, 2016 5:57 PM, quenthal notifications@github.com wrote:For example when wanting to to change channel 23, I'd like to be able to sent keypresses 0, 2 and 3 to required device.

**Comment by quenthal** [comment]
Yeah, currenly solving this by making sequences in Harmony App. However, with this capability directly in the interface one could make dynamic sequences depending on states of other items - when integrating restful-harmony to other home-automation items.

**Comment by bwssytems** [comment]
I was confused on which repository issue I was replying too...lol The ha-bridge has this built in, but the restful-harmony requires you to send three different calls to the API. Sorry for the misunderstanding.

So, I can add the same type of processing that the ha-bridge has and send an array of instructions in the call.

**Comment by quenthal** [comment]
That sounds good!
