### ISSUE TITLE
activities/special home automation buttons on harmony remote ultimate

### ISSUE THREAD

**Issue by dghh** [bwssytems/restful-harmony#8]
Hi,
i´m using the restful-harmony for a few days now. I have only one issue with it.
On my remote there are this special buttons for home automation. A call with the restful-harmony to show devices or activities don´t show the buttons or even activities which include one of these buttons.

**Comment by bwssytems** [comment]
So far, for those buttons on the remote itself , no one has looked into reverse engineering that api. They do not come through the current discovered api. Since the api works for most, no one has spent the time to do a wire shark and get the info, including me.
